# Generated by Django 5.0 on 2023-12-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_activity_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(related_name='assignments', to='record.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(related_name='exams', to='record.student'),
        ),
    ]
