# Generated by Django 5.0 on 2023-12-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_assignment_students_exam_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='students', to='record.course'),
        ),
    ]
